# Write a program "nearly_equal.py" to check whether two given strings are nearly equal. Two strings a and b are nearly equal when a can be generated by a single mutation on b. 
# For example,
# if str1="'python", str2="'perl", it should return False, 
# if  str1="'python", str2="jython", it should return True, and
# if  str1="man", str2="'woman", it should return False.

